version: "3.9"
services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--port", "27017"]
    volumes:
      - mongo_data:/data/db
    
  
  catalog.api:
    build:
      context: .
      dockerfile: /src/Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
  
 
  
  
    
  basketdb:
    image: redis
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  
  
  basket.api:
    build:
      context: .
      dockerfile: /src/Services/Basket/Basket.API/Dockerfile
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:CacheUrl=basketdb:6379,abortConnect=false"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://admin:password@rabbitmq:5672"
      
    ports:
      - "8001:80"
    depends_on:
      - basketdb
      - rabbitmq
    
  discountdb:
    image: postgres
    restart: always
    container_name: discountdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USER : admin
      POSTGRES_DB: DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  discount.api:
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      
    ports:
      - "8002:80"
    depends_on:
      - discountdb
    
  discount.grpc:
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8003:80"
    depends_on:
      - discountdb
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aspnetrun.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    restart:  always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data  
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
      SA_PASSWORD : "SwN12345678"
      ACCEPT_EULA : "Y"
    restart: always
    ports:
      - "1433:1433"
  order.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678; TrustServerCertificate=True;"
      -  "EventBusSettings:HostAddress=amqp://admin:password@rabbitmq:5672"
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"
  rabbitmq:
    container_name: rabbitmq
    image : rabbitmq:3.12-rc-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  ocelotapigw:
    container_name: ocelotapigw
    image: ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGw/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api
  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      -  "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    build:
      context: .
      dockerfile: src/ApiGateways/Shopping.Aggregator/Shopping.Aggregator/Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api
    ports:
      - "8005:80"
  client.app:
    container_name: client.app
    build:
      context: .
      dockerfile: src/WebApps/AspnetRunBasics/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - order.api
    ports:
      - "8006:80"

volumes:
  mongo_data:
  portainer_data:
  postgres_data:  
  pgadmin_data:
  rabbitmq_data:
    
